version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=django_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  sgbd:
    image: dpage/pgadmin4
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
volumes:
  postgres_data: